export const SEEDED_EXPLORE_EVENT_JOIN_KEY = "lynk:seededExploreEventJoins";

export const seededExploreEvents = [
  {
    id: "explore-padel-open-match",
    title: "Padel Open Match",
    location: "PadelPadel Aarhus",
    date: "I dag · 18:00",
    tag: "Padel",
    activity_type: "padel",
    participants: 3,
    capacity: 4,
    spots: "3/4",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:00:00.000Z",
    image: "https://loremflickr.com/900/650/padel,people?lock=101",
    description:
      "Åben padelmatch for spillere der har lyst til en hyggelig og jævnbyrdig kamp.",
  },
  {
    id: "explore-brabrand-run",
    title: "Løb rundt om Brabrand Sø",
    location: "Brabrand Sø",
    date: "I morgen · 19:00",
    tag: "Løb",
    activity_type: "løb",
    participants: 11,
    capacity: 15,
    spots: "11/15",
    level: "Aktiv",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:01:00.000Z",
    image: "https://loremflickr.com/900/650/running,group?lock=102",
    description:
      "Social løbetur rundt om Brabrand Sø i et stabilt tempo med plads til fællesskab undervejs.",
  },
  {
    id: "explore-onsdagsfodbold",
    title: "Onsdagsfodbold",
    location: "Lyseng IF",
    date: "Ons 10 Jun · 20:00",
    tag: "Fodbold",
    activity_type: "fodbold",
    participants: 12,
    capacity: 14,
    spots: "12/14",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:02:00.000Z",
    image:
      "https://images.pexels.com/photos/32991511/pexels-photo-32991511.jpeg?auto=compress&cs=tinysrgb&w=900",
    description:
      "Uformel onsdagsfodbold på Lyseng IF. Vi deler hold på dagen og spiller for hyggen.",
  },
  {
    id: "explore-aarhus-street-basket",
    title: "Aarhus Street Basket",
    location: "Havneparken Aarhus Ø",
    date: "I morgen · 17:00",
    tag: "Basketball",
    activity_type: "basketball",
    participants: 7,
    capacity: 10,
    spots: "7/10",
    level: "Aktiv",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:03:00.000Z",
    image: "https://loremflickr.com/900/650/basketball,street?lock=104",
    description:
      "Street basket ved havnen med korte kampe og rotation, så alle får masser af spilletid.",
  },
  {
    id: "explore-morgenpadel-mix",
    title: "Morgenpadel Mix",
    location: "Match Padel Aarhus",
    date: "I morgen · 07:30",
    tag: "Padel",
    activity_type: "padel",
    participants: 2,
    capacity: 4,
    spots: "2/4",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:04:00.000Z",
    image: "https://loremflickr.com/900/650/padel,amateur?lock=105",
    description:
      "Start dagen med en frisk padelmatch. Vi mixer holdene efter niveau og energi.",
  },
  {
    id: "explore-5k-social-run",
    title: "5K Social Run",
    location: "Universitetsparken",
    date: "Lør 6 Jun · 10:30",
    tag: "Løb",
    activity_type: "løb",
    participants: 14,
    capacity: 20,
    spots: "14/20",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:05:00.000Z",
    image: "https://loremflickr.com/900/650/jogging,park?lock=216",
    description:
      "Rolig 5 km social run i Universitetsparken. Fokus er fællesskab og en god tur.",
  },
  {
    id: "explore-sondagsbold",
    title: "Søndagsbold",
    location: "Viby IF Kunstgræs",
    date: "Søn 7 Jun · 10:00",
    tag: "Fodbold",
    activity_type: "fodbold",
    participants: 10,
    capacity: 14,
    spots: "10/14",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:06:00.000Z",
    image:
      "https://images.pexels.com/photos/35481342/pexels-photo-35481342.jpeg?auto=compress&cs=tinysrgb&w=900",
    description:
      "Søndagsbold på kunstgræs i Viby. Kom som du er, så finder vi holdene på banen.",
  },
  {
    id: "explore-basket-ved-dokk1",
    title: "Basket ved Dokk1",
    location: "Dokk1 Basketbane",
    date: "I dag · 16:30",
    tag: "Basketball",
    activity_type: "basketball",
    participants: 5,
    capacity: 10,
    spots: "5/10",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:07:00.000Z",
    image:
      "https://images.pexels.com/photos/32885617/pexels-photo-32885617.jpeg?auto=compress&cs=tinysrgb&w=900",
    description:
      "Drop-in basket ved Dokk1. Vi spiller små hold og skifter løbende.",
  },
  {
    id: "explore-padel-let-ovede",
    title: "Padel for Let Øvede",
    location: "PadelPadel Aarhus",
    date: "Lør 6 Jun · 15:00",
    tag: "Padel",
    activity_type: "padel",
    participants: 3,
    capacity: 4,
    spots: "3/4",
    level: "Aktiv",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:08:00.000Z",
    image: "https://loremflickr.com/900/650/padel,court?lock=109",
    description:
      "Padel for let øvede spillere der gerne vil have tempo og gode dueller.",
  },
  {
    id: "explore-tempo-run-8km",
    title: "Tempo Run 8 km",
    location: "Marselisborg Skovene",
    date: "Man 8 Jun · 18:00",
    tag: "Løb",
    activity_type: "løb",
    participants: 6,
    capacity: 10,
    spots: "6/10",
    level: "Seriøst",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:09:00.000Z",
    image: "https://loremflickr.com/900/650/running,club?lock=110",
    description:
      "8 km tempotur i Marselisborg Skovene for dig der vil have lidt mere fart i benene.",
  },
  {
    id: "explore-fredagskamp-7-mands",
    title: "Fredagskamp 7-mands",
    location: "AGF Træningsanlæg",
    date: "Fre 5 Jun · 17:00",
    tag: "Fodbold",
    activity_type: "fodbold",
    participants: 13,
    capacity: 14,
    spots: "13/14",
    level: "Aktiv",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:10:00.000Z",
    image: "https://loremflickr.com/900/650/soccer,team?lock=111",
    description:
      "Fredagskamp på 7-mandsbane. Der mangler få spillere til en god, intens kamp.",
  },
  {
    id: "explore-open-gym-basketball",
    title: "Open Gym Basketball",
    location: "Vejlby-Risskov Hallen",
    date: "Tir 9 Jun · 19:30",
    tag: "Basketball",
    activity_type: "basketball",
    participants: 8,
    capacity: 12,
    spots: "8/12",
    level: "Aktiv",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:11:00.000Z",
    image: "https://loremflickr.com/900/650/basketball,gym?lock=112",
    description:
      "Open gym basketball med opvarmning, småspil og kampe på tværs af niveau.",
  },
  {
    id: "explore-padel-pizza",
    title: "Padel & Pizza",
    location: "Match Padel Aarhus",
    date: "Fre 5 Jun · 18:30",
    tag: "Padel",
    activity_type: "padel",
    participants: 2,
    capacity: 4,
    spots: "2/4",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:12:00.000Z",
    image:
      "https://images.pexels.com/photos/28243528/pexels-photo-28243528.jpeg?auto=compress&cs=tinysrgb&w=900",
    description:
      "En afslappet omgang padel efterfulgt af pizza. Eventet er fyldt, men kan stadig åbnes.",
  },
  {
    id: "explore-recovery-run",
    title: "Recovery Run",
    location: "Aarhus Ø Strandpromenade",
    date: "I morgen · 09:00",
    tag: "Løb",
    activity_type: "løb",
    participants: 7,
    capacity: 12,
    spots: "7/12",
    level: "Casual",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:13:00.000Z",
    image: "https://loremflickr.com/900/650/running,people?lock=114",
    description:
      "Let recovery run langs Aarhus Ø. Lav intensitet, god snak og frisk luft.",
  },
  {
    id: "explore-aftenbold-risskov",
    title: "Aftenbold i Risskov",
    location: "Risskov Kunstgræs",
    date: "Tor 11 Jun · 20:00",
    tag: "Fodbold",
    activity_type: "fodbold",
    participants: 11,
    capacity: 14,
    spots: "11/14",
    level: "Aktiv",
    isSeededExploreEvent: true,
    created_at: "2026-06-03T08:14:00.000Z",
    image:
      "https://images.pexels.com/photos/30393837/pexels-photo-30393837.jpeg?auto=compress&cs=tinysrgb&w=900",
    description:
      "Aftenbold på Risskov Kunstgræs med tempo, men stadig plads til alle der vil spille seriøst og fair.",
  },
];

export function getSeededExploreEvent(eventId) {
  return seededExploreEvents.find((event) => event.id === eventId) || null;
}
